baseURL = 'http://example.org/'
languageCode = 'ro'
title = 'Asociația ȘTIM'
theme = "hugo-universal-theme"
themesDir = "./themes"


summatyLength = 70
paginate = 10

style = "default"


[menu]

[[menu.main]]
	name = "Despre noi"
	url = "/about"
	identifier = "menu.home"
	weight = 1

[[menu.main]]
	name = "Donează"
	url = "/donate"
	weight = 2
	identifier = "menu.donate"

[[menu.main]]
	name = "Evenimente"
	url = "/events"
	weight = 3
	identifier = "menu.events"

[[menu.main]]
	name = "Contact"
	url = "/contact"
	weight = 4
	identifier = "menu.contact"

[[menu.main]]
	name = "Membrii"
	parent = "menu.home"
	url = "/members"
	weight = 1

[[menu.main]]
	name = "Scop"
	parent = "menu.home"
	url = "/purpouse"
	weight = 2

[[menu.main]]
	name = "Istoric"
	parent = "menu.home"
	url = "/history"
	weight = 3

[[menu.main]]
	name = "Pagini Personale"
	parent = "menu.home"
	url = "/pages"
	weight = 4

[[menu.main]]
	name = "Proiecte"
	parent = "menu.events"
	url = "/projects"
	weight = 1

[[menu.main]]
	name = "Media"
	parent = "menu.events"
	url = "/media"
	weight = 2

[[menu.main]]
	name = "Olimpiade"
	parent = "menu.events"
	url = "/olimp"
	weight = 4

[params]
	logo = "img/STIM.png"
	logo_small = "img/STIM.png"
	contact_url = "/contact"
	mainSections = ["members", "olimp", "projects"]

[params.topbar]
	enable = true
	text = """<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
	<p class="hidden-md hidden-lg"><a href="tel:+420 777 555 333" data-animate-hover="pulse"><i class="fas fa-phone"></i></a>
	<a href="mailto:hello@universal.com" data-animate-hover="pulse"><i class="fas fa-envelope"></i></a>
	</p>
	"""

[params.widgets]
	categories = true
	tags = true
	search = true

[params.carouselCustomers]
	items = 6
	auto_play = false
	slide_speed = 2000
	pagination_speed = 1000

[params.carouselTestimonials]
	items = 4
	auto_play = false
	slide_speed = 2000
	pagination_speed = 1000

[params.carouselHomepage]
	enable = true
	auto_play = true
	slide_speed = 2000
	pagination_speed = 1000

[[menu.topbar]]
	weight = 2
	name = "GitHub"
	url = "https://github.com/devcows/hugo-universal-theme"
	pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
	weight = 3
	name = "Facebook"
	url = "http://facebook.com"
	pre = "<i class='fab fa-2x fa-facebook'></i>"

[[menu.topbar]]
	weight = 4
	name = "Twitter"
	url = "http://twitter.com"
	pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
	weight = 5
	name = "Email"
	url = "mailto:hello@universal.com"
	pre = "<i class='fas fa-2x fa-envelope'></i>"

[params.see_more]
	enable = true
	icon = "far fa-file-alt"
	title = "Află mai multe"
	subtitle = "TODO"
	link_url = "#"
	link_text = "TODO"

[params.clients]
	enable = true
	title = "Our Clients"
	subtitle = ""

[params.recent_posts]
	enable = true
	title = "From our blog"
	subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
	hide_summary = false

[params.footer.recent_posts]
	enable = true
